#!/bin/bash

rm -r 0
foamCleanPolyMesh
foamListTimes -rm

blockMesh
decomposePar
mpirun -np 4 snappyHexMesh -overwrite -parallel

reconstructParMesh -constant

setSet -batch ./system/setSet
createPatch -overwrite -dict ./system/createPatchDict

rm -r 0
cp -r 0.orig 0

setFields
decomposePar
mpirun -np 4 interFoam -parallel